name: overlayment
description: Show a dialog, notification, window, or a panel easily. use helping widgets like AutoComplete, Expander(Dropdown).
version: 0.1.0
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
